name: example
version: 0.0.0

publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  env_annotation:
    git:
      url: https://github.com/Hecatoncheir/env_configurable.dart.git
      path: env_annotation

dev_dependencies:
  analyzer: 8.0.0
  dart_code_linter: ^3.0.0
  test: ^1.26.3
  build_runner: ^2.6.0
  build_test: ^3.3.0

  env_configurable:
    git:
      url: https://github.com/Hecatoncheir/env_configurable.dart.git
      path: env_configurable

dependency_overrides:
  analyzer: 8.0.0
  env_annotation:
    path: ../env_annotation
  env_configurable:
    path: ../env_configurable
