name: example
version: 0.0.0

publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  env_annotation:
    git:
      url: https://github.com/Hecatoncheir/env_configurable.dart.git
      path: env_annotation

dev_dependencies:
  analyzer: 10.0.1
  dart_code_linter: any
  test: any
  build_runner: any
  build_test: any

  env_configurable:
    git:
      url: https://github.com/Hecatoncheir/env_configurable.dart.git
      path: env_configurable

dependency_overrides:
  env_annotation:
    path: ../env_annotation
  env_configurable:
    path: ../env_configurable
