# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
# https://dart-lang.github.io/linter/lints/index.html.
analyzer:
  enable-experiment:
    - non-nullable
  plugins:
    - dart_code_metrics

  cannot-ignore:
    - error
    - unused_import

  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

linter:
  rules:
    avoid_print: true
    always_declare_return_types: true
    always_put_control_body_on_new_line: false
    always_put_required_named_parameters_first: true
    always_require_non_null_named_parameters: true
    always_specify_types: false
    annotate_overrides: true

    avoid_annotating_with_dynamic:
      exclude:
        - test/**

    avoid_as: false
    avoid_bool_literals_in_conditional_expressions: false
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true
    avoid_classes_with_only_static_members: true
    avoid_double_and_int_checks: true
    avoid_empty_else: true
    avoid_function_literals_in_foreach_calls: true
    avoid_implementing_value_types: true
    avoid_init_to_null: true
    avoid_js_rounded_ints: true
    avoid_null_checks_in_equality_operators: true
    avoid_positional_boolean_parameters: true
    avoid_private_typedef_functions: true
    avoid_relative_lib_imports: true
    avoid_renaming_method_parameters: true
    avoid_return_types_on_setters: true
    avoid_returning_null: true
    avoid_returning_null_for_void: true
    avoid_returning_this: true
    avoid_setters_without_getters: false
    avoid_single_cascade_in_expression_statements: true
    avoid_slow_async_io: true
    avoid_types_as_parameter_names: true
    avoid_types_on_closure_parameters: false
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    await_only_futures: true
    camel_case_types: true
    cancel_subscriptions: true
    cascade_invocations: false
    close_sinks: true
    comment_references: true
    constant_identifier_names: true
    control_flow_in_finally: true
    curly_braces_in_flow_control_structures: true
    directives_ordering: false
    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true
    file_names: true
    flutter_style_todos: false
    hash_and_equals: true
    implementation_imports: true
    invariant_booleans: true
    iterable_contains_unrelated_type: true
    join_return_with_assignment: false
    library_names: true
    library_prefixes: true
    lines_longer_than_80_chars: true
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    non_constant_identifier_names: true
    null_closures: true
    omit_local_variable_types: false
    one_member_abstracts: true
    only_throw_errors: true
    overridden_fields: true
    package_api_docs: true
    package_names: true
    package_prefixed_library_names: true
    parameter_assignments: true
    prefer_adjacent_string_concatenation: true
    prefer_asserts_in_initializer_lists: true
    prefer_conditional_assignment: true
    prefer_const_constructors: false
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_constructors_over_static_methods: false
    prefer_contains: true
    prefer_equal_for_default_values: true
    prefer_expression_function_bodies: false
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_foreach: false
    prefer_function_declarations_over_variables: false
    prefer_generic_function_type_aliases: true
    prefer_initializing_formals: true
    prefer_int_literals: true
    prefer_interpolation_to_compose_strings: false
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    prefer_mixin: true
    prefer_spread_collections: true
    prefer_single_quotes: true
    prefer_double_quotes: false
    prefer_typing_uninitialized_variables: true
    prefer_void_to_null: true
    public_member_api_docs: false
    recursive_getters: true
    slash_for_doc_comments: true
    sort_constructors_first: false
    sort_pub_dependencies: false
    sort_unnamed_constructors_first: true
    test_types_in_equals: true
    throw_in_finally: true
    type_annotate_public_apis: true
    type_init_formals: true
    unawaited_futures: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_statements: true
    unnecessary_this: false
    unrelated_type_equality_checks: true
    use_rethrow_when_possible: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    use_to_and_as_if_applicable: true
    valid_regexps: true
    void_checks: true

dart_code_metrics:
  anti-patterns:
    #    - long-method
    - long-parameter-list
  metrics:
    cycloramic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    #    - avoid-late-keyword
    #    - avoid-non-null-assertion
    - avoid-unused-parameters
    - binary-expression-operand-order
    - double-literal-format
    - member-ordering:
        exclude:
          - test/**
    - member-ordering-extended:
        exclude:
          - test/**
    - newline-before-return:
        exclude:
          - test/**
    - no-boolean-literal-compare
    - no-empty-block
    #    - no-equal-arguments:
    #        ignored-parameters:
    #          - height
    #          - width
    - no-equal-then-else
    - no-magic-number:
        exclude:
          - test/**
          - lib/ui/**
    # - no-object-declaration
    - prefer-conditional-expressions
    - prefer-trailing-comma:
        exclude:
          - test/**
    # Flutter specific
    - always-remove-listener
    #    - avoid-returning-widgets
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - prefer-extracting-callbacks
    # Intl specific
    - prefer-intl-name
    - provide-correct-intl-args
