name: env_configurable
description: Generate class with properties from environment variables..
version: 3.0.0

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_code_linter: ^3.0.0
  build_runner: ^2.6.0
  source_gen: ^3.0.0
  recase: ^4.1.0

  env_annotation:
    git:
      url: https://github.com/Hecatoncheir/env_configurable.dart.git
      path: env_annotation
      ref: 3.0.0

dev_dependencies:
  build_test: ^3.3.0
  test: ^1.26.3
