name: env_configurable
description: Generate class with properties from environment variables..
version: 1.0.0

publish_to: "none"

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build: ^2.4.0
  source_gen: ^1.3.1
  recase: ^4.1.0

  env_annotation:
    git:
      url: https://github.com/Hecatoncheir/env_configurable.dart.git
      path: env_annotation

dev_dependencies:
  test: ^1.24.2
  build_test: ^2.1.7
  build_runner: ^2.4.2
  dart_code_metrics: ^5.7.3
