name: env_configurable
description: Generate class with properties from environment variables..
version: 2.0.0

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  recase: ^4.1.0

  env_annotation:
    git:
      url: https://github.com/Hecatoncheir/env_configurable.dart.git
      path: env_annotation

dev_dependencies:
  build: ^2.4.0
  build_runner: ^2.4.4
  build_config: ^1.1.1
  source_gen: ^1.3.2
  build_test: ^2.1.7
  test: ^1.24.2
  dart_code_metrics: ^5.7.3
